pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - author=dependabot[bot]
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.hydra-spec
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.mergify
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.mergify-check
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.ny
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.ny-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-arabic
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-arabic-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-armenian
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-armenian-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-compact
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-compact-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-georgian
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-georgian-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-hebrew
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-hebrew-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-mono
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-mono-nerd
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-pro
  - check-success*=ci/hydra:apple-fonts:*:aarch64-linux.sf-pro-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.hydra-spec
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.mergify
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.mergify-check
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.ny
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.ny-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-arabic
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-arabic-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-armenian
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-armenian-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-compact
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-compact-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-georgian
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-georgian-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-hebrew
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-hebrew-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-mono
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-mono-nerd
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-pro
  - check-success*=ci/hydra:apple-fonts:*:x86_64-linux.sf-pro-nerd
  name: Automatically merge dependabot updates
